app = "gochop-backend"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  BASE_URL = "https://gochop-backend.fly.dev"
  NEXTAUTH_SECRET = "your-super-secret-key-change-this-in-production"
  
[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512 