name: Deploy to Fly.io

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy-redis:
    name: Deploy Redis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Redis
        run: |
          cd redis
          flyctl deploy --remote-only

  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    needs: deploy-redis
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Backend
        run: |
          cd backend
          flyctl deploy --remote-only
